### ISSUE TITLE
Export Models fails on BCIF from ModelServer

### ISSUE THREAD

**Issue by midlik** [molstar/molstar#1040]
When I download model from https://www.ebi.ac.uk/pdbe/model-server/v1/6wvp/atoms?auth_asym_id=B&encoding=bcif,
it shows OK in Mol* Viewer, but when I try to export model (via the right hand control panel), I get this error:
```
Model export failed. See console for details.
```

And the console says:
```
molstar.js:2 Error: unreachable
    at he (molstar.js:2:1773657)
    at Ql (molstar.js:2:2087019)
    at molstar.js:2:2085120
    at hl (molstar.js:2:2085190)
    at dl (molstar.js:2:2084359)
    at molstar.js:2:2189142
    at Object.getField (molstar.js:2:2189609)
    at Ha.get [as program_version] (molstar.js:2:1993792)
    at molstar.js:2:2090663
    at Ol (molstar.js:2:2101530)
```
![download](https://github.com/molstar/molstar/assets/14818844/880188ff-61e0-4392-88ae-2f61fc92d1d8)
![export](https://github.com/molstar/molstar/assets/14818844/fb00d80b-9674-492b-a060-da62fb03490b)

When I try the same with encoding=cif, the export works fine.

**Comment by midlik** [comment]
Getting the data from a different ModelServer instance doesn't help (https://models.rcsb.org/v1/6wvp/atoms?auth_asym_id=B&encoding=bcif)

**Comment by dsehnal** [comment]
#1048 should address this

**Comment by JonStargaryen** [comment]
Weighing in because this also affects the Java codec and isn't as easy to fix... I think this might be an issue in the ModelServer code. A while back I saw that ModelServer will chain ByteArray encodings together, which doesn't make sense and interestingly doesn't happen when the viewer or cif2bcif is used to create a BinaryCIF file.

I wanted to dig into this for quite a while now but didn't find the time yet. Maybe someone has an idea.

![double-ba](https://github.com/molstar/molstar/assets/9744615/86bf68b5-c56a-443a-bcba-63b1f0bc00fe)

**Comment by dsehnal** [comment]
The cif2bcif works differently. The bug will be either in the determination heuristic for the "schema-based cif fields" or error in manually assigning the encoding for this particular field. Probably gonna be the first one.

**Comment by dsehnal** [comment]
I managed to find the issues (or at least some of them to make this work). See https://github.com/molstar/molstar/pull/1057
