### ISSUE TITLE
 How can i judge the multiple conformations of a certain residue?

### ISSUE THREAD

**Issue by luckyxutao** [molstar/molstar#1164]
from selection to residue list with conformations
```js
      const selections = Array.from(this.molstarRef.current.getPlugin().managers.structure.selection.entries.values());
      const chains = [];
      const resdueList = [];
      for (const { structure } of selections) {
        if (!structure) continue;

        Structure.eachAtomicHierarchyElement(structure, {
          chain: (loc) => {
            chains.push(StructureProperties.chain.auth_asym_id(loc));
          },
          atom: (loc) => {
            console.log('conformation', loc);
          },
          residue: (loc) => {
            // const stat = StructureElement.Stats.ofLoci(loc);
            resdueList.push({
              label_seq_id: StructureProperties.residue.label_seq_id(loc),
              label_comp_id: StructureProperties.atom.label_comp_id(loc),
              // stat,
              // label_comp_id: StructureProperties.residue.label_comp_id(loc),
            });
          },
        });
      }

```

![image](https://github.com/molstar/molstar/assets/1294316/9e1c34c1-6e5c-4ada-b8de-22478be06a53)
![image](https://github.com/molstar/molstar/assets/1294316/39e8b8e5-d27a-46c1-80e4-1f42121c1484)
Thank you for your help.
Best Regards

**Comment by dsehnal** [comment]
Either entire or parts of a residue can have alternate locations. You can access this information via `StructureProperties.atom.label_alt_id` and `.atom.occupancy`. 

You might have to do the residue grouping in the `atom` callback and use `StructureProperties.residue.key` to get residue indices of the residues that have the alternate locations (since not all atoms within a residue always have these).

**Comment by luckyxutao** [comment]
Hi,

Thank you very much for your help. It was exactly what I needed !!

Best Regards,
