### ISSUE TITLE
Model slider from multiple pdb files (instead of one ensembled pdb)

### ISSUE THREAD

**Issue by ajivanyan-deeporigin** [molstar/molstar#1235]
Hi! 
Currently we have the functionality to handle pdb files with multiple models in it. It renders a trajectory control panel to navigate between models. 

<img width="231" alt="Screenshot 2024-08-22 at 18 25 03" src="https://github.com/user-attachments/assets/8d4d4af0-a925-41d5-afd0-90a12b0c01fc">

I am looking for a way to achieve the same trajectory controls for multiple pdb files instead of one ensembled pdb file. If there is no functionality yet, would be great to have it.

**Comment by ajivanyan-deeporigin** [comment]
https://github.com/molstar/molstar/issues/1234
looks similar

**Comment by dsehnal** [comment]
You would have to write this yourself. The `PluginUISpec` allows a lot of customization in replacing individual UI components.

**Comment by ajivanyan-deeporigin** [comment]
@dsehnal  I tried to find a mechanism which I can reuse to write this feature, but it looks like there is no unified structure to achieve this slider functionality to reuse. Any guidance towards how to implement this functionality and where to start will be much appreciated.

**Comment by ajivanyan-deeporigin** [comment]
If this goes well and I get it working, I will be happy to contribute to the project

**Comment by dsehnal** [comment]
You need to

- Write your own [TrajectoryViewportControls](https://github.com/molstar/molstar/blob/master/src/mol-plugin-ui/controls.tsx#L30). Instead of a single control, you will just render multiple ones based on `this.plugin.managers.structure.hierarchy.current.trajectories` data. Add something like `this.subscribe(this.plugin.managers.structure.hierarchy.behaviors.selection, this.update);` to make sure the UI is synced.
- Write your own [DefaultViewport](https://github.com/molstar/molstar/blob/master/src/mol-plugin-ui/plugin.tsx#L268) where you use the component from above.
- The the viewpoint from above in `PluginUISpec.components.viewer.view` (just pass the class or function component (if you use hooks) object) when creating your plugin instance.
