### ISSUE TITLE
Help porting code from NGL

### ISSUE THREAD

**Issue by delarosatrevin** [molstar/molstar#1236]
I'm adding 3D visualization to a web application for CryoEM data management and processing.  I have done some tests with NGL, rendering the 3D volume by providing the data array and dimensions. I encountered a rendering issue when accessing from MacOS (both Chrome and Safari browsers). I'm not sure if it's a Three.js issue or something else. So, I decided to try to update my code to use Mol*. 

My javascript code for embedding the NGL viewer (plus a simple slider to change the surface level) is the following: 

```javascript
function renderVolume3D(containerId, arrayJson, dimensions) {
    //var data = JSON.parse(dataJson);
    var array = new Uint8Array(atob(arrayJson).split("").map(function (c) {
            return c.charCodeAt(0);
        }));

        console.log("array[0]: " + array[0] + " array[1000]: " + array[1000]);

        const nx = dimensions[0], ny = dimensions[1], nz = dimensions[2];
        const cx = nx / 2, cy = ny / 2, cz = nz / 2;
        var volume = new NGL.Volume("volume", '', array, nx, ny, nz);
        var stage = new NGL.Stage(containerId);
        var volComp = stage.addComponentFromObject(volume);
        var surface = volComp.addRepresentation("surface",
            {isolevelType: 'value', isolevel: 180});
        volComp.setPosition([-cx, -cy, -cz]);

        const sliderId = '#' + containerId + "_slider";

        $(sliderId).val(surface.getParameters()['isolevel']);
        $(sliderId).on("input", function() {
            surface.setParameters({isolevel: parseInt($(this).val())});
        });
} // function renderVolume3D
```

I'm interested (for now) in embedding the 3D canvas rather than the whole Mol* UI. Could anyone please give me some directions about doing the previous task in Mol*?

Is there a CDN URL for adding Mol* to another application?

Thanks in advance for your support.

**Comment by dsehnal** [comment]
This will currently require a bit more code in Mol* and won't be possible without making a custom build with a bundler such as `esbuild`. If this is an option for you, I can help you write the script.

**Comment by delarosatrevin** [comment]
Hi @dsehnal, Thanks for the reply. I don't mind that it requires more code. 

Does the custom-build bundler mean I must create a bundle, which I can then distribute with my application? 

If I need to change the Mol* code from my side, will I need to create a new bundle?

Anyway, I'm open to exploring this option, and I would greatly appreciate any help/guidance.

**Comment by dsehnal** [comment]
Essentially you would do something like this:

- (`npm init`) `npm install molstar`, `npm install esbuild`
- Create `index.js` (or `.ts`) file that imports some code from mol* and exports a function that renders your volume and allows to change the iso-value
- `esbuid src/index.js <some params> build/index.js`
- Host the `build/index.js` file, embed it with `<script />` tag in your app, and use the functions you've defined

**Comment by delarosatrevin** [comment]
Ok, I can try to do that. What would be the code in Mol* to achieve the same as my 'renderVolume3D' function?

**Comment by dsehnal** [comment]
I think I will add this to the docs for the `esbuild` setup to https://molstar.org/docs/ as an example since this kind of question gets asked quite often. Give me a few days for this please.

For would take me some time to create a fully working example as well (might use it in the docs), but if you want to try it yourself in the meantime, here are some pointers:

- Define a transform that maps your bases data to an volume object, similar to say [this one](https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/transforms/volume.ts#L33)
  - Another example is here [here](https://github.com/molstar/molstar/blob/master/src/extensions/alpha-orbitals/transforms.ts#L26)  or you can define your own namespace with `const MyTransforms = StateTransformer.builderFactory('my-namespaces');
const Xform = MyTransforms(...)();`
- Call `VolumeRepresentation3D` on that using `const repr = await pluing.build().toRoot().apply(MyNewXform, { params }).apply(VolumeRepresentation3D, { params }).commit()`
  - `createVolumeRepresentationParams` function is helpful in obtaining the params.
- Use `plugin.build().to(repr).update(...).commit()` to update the iso value with your slider

**Comment by dsehnal** [comment]
Early preview of the docsd before it gets merged, the docs are here https://github.com/molstar/molstar/pull/1242. It should be enough to get you started (if you haven't already :) )

- Example of building Volume.Data from custom source: https://github.com/molstar/molstar/blob/master/src/extensions/alpha-orbitals/transforms.ts#L90
- The [Alpha-orbitals example](https://molstar.org/demos/alpha-orbitals/) show how to load the volume and add UI component that controls it https://github.com/molstar/molstar/blob/master/src/examples/alpha-orbitals/index.ts. You should be able to extract the code you need and use your custom UI instead of react if  you want too.

**Comment by delarosatrevin** [comment]
Looks great! I will try it as soon as possible—many thanks for your support.

**Comment by dsehnal** [comment]
The docs are now available at https://molstar.org/docs/plugin/custom-library/
