### ISSUE TITLE
A memory allocation bug when loading the trajectory

### ISSUE THREAD

**Issue by hdb106** [molstar/molstar#1258]
[C2H6-demo.zip](https://github.com/user-attachments/files/16925373/C2H6-demo.zip)
Hello, I encountered the following error while loading trajectory files with molstar: 
<img width="1280" alt="96bf7b9a62069c230291aa750c74031" src="https://github.com/user-attachments/assets/0aa4580c-3b0e-4048-84a1-ad3c9e5ad992">

the .xtc file is obtained by converting the .xyz file using the mdtraj Python package, it can be opened with both VMD and OVITO, and the .pdb file can also be opened with PyMOL and VMD. However, when trying to load the trajectory with both, there is a bug that causes excessive memory allocation. Why does this happen?

**Comment by dsehnal** [comment]
I was able to load your files by doing this fix https://github.com/molstar/molstar/pull/1260

I wasn't able to loading the PDB file though, so instead I just used the 1st snapshot from the XYZ source. Loading this PDB might require specific support, because currently it seems to be messing up the atom types.

![image](https://github.com/user-attachments/assets/d10425da-a661-40ff-9b58-7775085db1cc)
