### ISSUE TITLE
StructureElement.Loci.isSubset(haystack, needle) can return true when needle contains units that are not present in haystack

### ISSUE THREAD

**Issue by papillot** [molstar/molstar#1292]
Just reporting this as I was surprised by the result.
The "shape" of the function is declared like this:
```ts
/** Check if second loci is a subset of the first */
    export function isSubset(xs: Loci, ys: Loci): boolean
```

I've written code that compared 2 Locis in the following way:
- `haystack` is a selection that contains a single unit with a single atom (a ZN ion)
- `needle` is a Loci that contains 3 units: 1 unit with water molecules, 1 unit with a single atom (a CA ion), 1 unit with a single atom (the same ZN ion as in the haystack)

The return value from `StructureElement.Loci.isSubset(haystack, needle)` is `true` which I found un-intuitive.
Note that the return value from `StructureElement.Loci.isSubset(needle, haystack)` is also `true` in this example, which looks correct.

This is due to the code that compares the elements between the 2 loci:
https://github.com/molstar/molstar/blob/fe502539f9ef554649b2fe0c2b48cba33dfd7a3b/src/mol-model/structure/structure/element/loci.ts#L268
If a unit from `needle` is not found in `haystack`, it is ignored in the comparison. The effect here is that `Loci.isSubset` behaves has `Loci.areIntersecting` at the level of the units (are there any units that intersect) and strict subSet at the level of the unit elements for the common units only.

This function is used only at one place in the whole codebase in relation with the LociSelectManager to toggle the selection content. It has been added to the codebase 5 years ago, so I guess that this behavior is relied upon.
I would suggest that at least this specification is documented in the function docstring, and maybe to add an optional flag to the function or create a separate function to check for subsets by considering all units in the comparison.

I can contribute to the code, just want to make sure in which direction to go.

**Comment by dsehnal** [comment]
Looking at this, it seems to be a case of either unfortunate naming when the goal was to achieve reasonable toggle behavior for selections or a copy-paste error from the `areIntersecting` code right above (looking at the [PR](https://github.com/molstar/molstar/commit/9aa375a45faedec88cb4d9cc11a07908948f3f0f) that introduced this, I would wager the latter :D ). Two options:

- Change the behavior for this to behave as you expect (instead of `continue`, `return false`)

Or:

- Schedule rename of `Loci.isSubset` to `Loci.hasUnitSubset` for v5 to not introduce a breaking change just in case someone relies on this (I believe the change is very small)
- Add `Loci.isStrictSubset` that implements the expected behavior

-----

I am inclined to just adjusting the implementation. @arose since you originally added this, does that sound ok?

**Comment by papillot** [comment]
Thanks @dsehnal for the input.
Another possibility without introducing any breaking change:
```ts
export function isSubset(xs: Loci, ys: Loci, compareOnlyCommonUnits = true): boolean {
        if (Loci.isEmpty(xs)) return Loci.isEmpty(ys);

        const map = new Map<number, OrderedSet<UnitIndex>>();

        for (const e of xs.elements) map.set(e.unit.id, e.indices);

        let isSubset = false;
        for (const e of ys.elements) {
            if (!map.has(e.unit.id)) { 
              if (compareOnlyCommonUnits) continue;
              return false;
            }
            if (!OrderedSet.isSubset(map.get(e.unit.id)!, e.indices)) return false;
            else isSubset = true;
        }

        return isSubset;
    }
```

**Comment by arose** [comment]
I am inclined to fix the isSubset function as it is clearly wrong(ish) and if need be provide another function for the single use case. I briefly played around with the UI to try to find an example where it actually makes a difference but came up short thus far.
