### ISSUE TITLE
Adding surface to visuals creates outlines on volume and surface reps that do not disappear

### ISSUE THREAD

**Issue by pechersky** [molstar/molstar#1326]
Here, I had a ligand and protein and volume rep. I added a surface rep of the volume to the scene. It made the volume wireframe rep have these thick lines. I then hid the surface, and rotated the view -- the surface outline and the thick volume wireframe lines remained in their original spot. Opening this state tree panel on the left cleans up the view. This all worked fine on v4.7.0, but started breaking on v4.8.0. I checked that v4.7.1 is fine, and local build of master is bad. Bisecting more.

![image](https://github.com/user-attachments/assets/3822569c-ebf7-47db-876b-ab5617ae895c)

**Comment by pechersky** [comment]
Setting `includeTransparent` in `pluginRef.current.canvas3d?.setProps({ postprocessing: {` fixes it in our use case, but I think it is just hiding the underlying issue.

**Comment by pechersky** [comment]
So it seems that there are related issues here:
- outlines for wireframes (that are transparent) are somehow not updating on rotation of the scene
- outlines for surfaces (that are transparent) are somehow sticking around when surface itself is hidden (and also do not rotate)
- a rep should have per-ref configuration whether to have an outline when it is transparent, instead of a global scene config

**Comment by arose** [comment]
@giagitom could you have a look at this? I suspect this is related to the transparent SSAO related refactoring.

**Comment by arose** [comment]
Thanks for reporting @pechersky

**Comment by giagitom** [comment]
Hi @pechersky, could you please share a state presenting the issue? I'm unable to reproduce it.

**Comment by rjdirisio** [comment]
Hi,

I narrowed the bug down slightly to an opacity setting issue in the wireframe rep. We do also observe the bug when the ligand surface is created, but I think more broadly it's because, on some canvas update, like what happens during surface generation (via addRepresentation), the refreshing is not fully working with the volume rep and the surface rep, particularly when they have some level of opacity.

I am attaching a `.txt` file that is actually a react `.tsx` file that I used to reproduce the issue. One can reproduce the issue by just changing the opacity of the electron density wireframe.

The string rep of the pdb that is loaded into the viewer is baked into the file. But, the ccp4 map used to create the volume rep is not. Instead, I am attaching the ccp4 map here as a zipped binary file. In the react app I used to run this, I placed the ccp4 map in the `public/` directory, which allows me in my react app to load the `arrayBuffer` like this:

```tsx
      // Note: ./ is pointing to public/ when react app is built
      const myDensity = `./7MQP_map.ccp4`;
      const resp = await fetch(myDensity);
      const buff = await resp.arrayBuffer();
```

What is crucial to the bug is that I **cannot** reproduce the error if I click and drag this  ccp4 map into the viewer and _then_ manually set a rep with opacity. Instead, one has to load it in + use the programmatic rep provided tsx file to reproduce the bug. As a reminder, this was reproduced with molstar 4.8.0, and we do not observe the issue in 4.7.0.


[7MQP_map.zip](https://github.com/user-attachments/files/17652627/7MQP_map.zip)
[molstarBug_tsx.txt](https://github.com/user-attachments/files/17652629/molstarBug_tsx.txt)

Here is a video of how the bug can be once the app is launched. Note, the pdb and map are loaded in when the app laucnhes:


https://github.com/user-attachments/assets/0888e13d-7b37-452d-873b-64557adbe6cd

**Comment by rjdirisio** [comment]
It's also worth noting that the molstar state / session export does not preserve the opacity of the wireframe. The opacity after export and reload into any viewer just changes the saturation of the color of the wireframe. So unfortunately I could not provide molx and molj files to reproduce this.

**Comment by giagitom** [comment]
Hi @rjdirisio thanks for the additional information, #1331 should fix the issue restoring the original behavior.

**Comment by rjdirisio** [comment]
That fix does seem solve the issue, thanks! 

It has created another problem for us, though, that I detail here:
https://github.com/molstar/molstar/discussions/1334#discussioncomment-11180983

Essentially, our wireframe rep now has a black outline, whereas previously it did not. We'd like to selectively choose which components have an outline (wireframe shouldn't have one, and surface should). We're not sure how to do that in the code in light of this change.

**Comment by pechersky** [comment]
The issue at hand has been solved -- perhaps later we can have per-rep options for outline.
