### ISSUE TITLE
Visualizing custom shapes.

### ISSUE THREAD

**Issue by hlvlad** [molstar/molstar#134]
Hello,

I'm trying to visualize some custom shapes in the viewer. For example, [here](https://github.com/hlvlad/molstar-shape-example/blob/main/src/cubes/representation.ts), [demo](https://hlvlad.github.io/molstar-shape-example/), I have array of point coordinates, and try to place spheres at each point, then connect them via cylinders. Cylinders are added properly, but colors and interactivity stop working after adding any single sphere. I would like to ask the following questions:

1. Am I doing something wrong, or there is limitation on number of vertices?
2. How can I fix zoom, so combined shape would fit on screen when I click on it? Bounding spheres seem to be generated properly.
3. If I have large array of vertices, is `MeshBuilder.addTriangle` correct way to build final Mesh ? (`SquareRepresentation` in example above).
4. Is there is any possibility to reference Tube 1 from Group 1 and Group 2 without rendering it twice?
5. How can I combine few shapes with different `alpha` value into single shape (State Tree node)? Also, how to change `pickingAlphaThreshold`?
6. How can I change representation3d of loaded molecule (from cartoon to ball&stick, for example) using external button like in basic_wrapper example?
7. Is it possible to alter Tube size parameter for all tubes created with `CreateTube` ([code](https://github.com/hlvlad/molstar-shape-example/blob/main/src/cubes/behavior.ts)) simultaneously?

Thank you in advance for response.

**Comment by dsehnal** [comment]
> 
> 
> Hello,
> 
> I'm trying to visualize some custom shapes in the viewer. For example, [here](https://github.com/hlvlad/molstar-shape-example/blob/main/src/cubes/representation.ts), [demo](https://hlvlad.github.io/molstar-shape-example/), I have array of point coordinates, and try to place spheres at each point, then connect them via cylinders. Cylinders are added properly, but colors and interactivity stop working after adding any single sphere. I would like to ask the following questions:
> 
>     1. Am I doing something wrong, or there is limitation on number of vertices?

There is no limitation to the number of vertices (other than few millions). There is however a bug with expanding the ``MeshBuilder`` size, because ``const builderState = MeshBuilder.createState(4096, 256, mesh);`` fixes your issue. I will have a look into this.

> 
>     2. How can I fix zoom, so combined shape would fit on screen when I click on it? Bounding spheres seem to be generated properly.

Please have a look at https://github.com/molstar/molstar/tree/master/src/extensions/rcsb/assembly-symmetry . It renders quite complicated/composed geometry from JSON data and annotation/zooming/.. works for it. 

![image](https://user-images.githubusercontent.com/21145776/109165735-3001b380-777c-11eb-8756-05597173e6ec.png)

> 
>     3. If I have large array of vertices, is `MeshBuilder.addTriangle` correct way to build final Mesh ? (`SquareRepresentation` in example above).

There is a ``Mesh`` which you can render directly. Check for example the gaussian surface representation. You can have multiple visuals per representation so the mesh and custom geometry be separate within a single visual.

Or use ``MeshBuilder.addPrimitive`` where you supply vertices, normals and triangle indices.

> 
>     4. Is there is any possibility to reference Tube 1 from Group 1 and Group 2 without rendering it twice?

I don't really understand the question. But maybe have some intermediate index that takes of of the linking?

> 
>     5. How can I combine few shapes with different `alpha` value into single shape (State Tree node)? Also, how to change `pickingAlphaThreshold`?

- For combined transparency, I think you currecntly need to use "overpaint". Try to figure out from the source code or perhaps @arose  will have more to say.
- For threshold, add 
```ts
components: {
    viewport: {
        canvas3d: {
            renderer: {
                pickingAlphaThreshold: 0.2,
            },
        },
    },
},
```

or 

```ts
this.plugin.canvas3d?.setProps(old => { old.renderer.pickingAlphaThreshold = 0.33; });
```

> 
>     6. How can I change representation3d of loaded molecule (from cartoon to ball&stick, for example) using external button like in basic_wrapper example?

In your ``loadStructureFromData`` save the reference to the representation returned by the last commit.
Then you can do 

```ts
pluing.build().to(selector).update(createStructureRepresentationParams(...));
```

In a button handler.

> 
>     7. Is it possible to alter Tube size parameter for all tubes created with `CreateTube` ([code](https://github.com/hlvlad/molstar-shape-example/blob/main/src/cubes/behavior.ts)) simultaneously?

- Add ``update``  to your transform, which runs ``createOrUpdate`` on the existing representation. There are numerous examples of this in ``mol-plugin-state`` (for example https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/transforms/representation.ts#L155)
- You can update multiple transforms at the same time like this:

```ts
const refsOrSelectorsToTubes = ...;
const update = pluing.build();
for (const tube of refsOrSelectorsToTubes) {
  update.to(tube).update(...);
}
await update.commit()
```

**Comment by dsehnal** [comment]
>     1. Am I doing something wrong, or there is limitation on number of vertices?

Update on this. Do ``builderState.currentGroup = 0;`` before adding the primites and it will work.

![image](https://user-images.githubusercontent.com/21145776/109173071-bb327780-7783-11eb-9c03-ecff86fb5bfd.png)

**Comment by arose** [comment]
Hey @hlvlad, did this solve your issue?

**Comment by hlvlad** [comment]
> Hey @hlvlad, did this solve your issue?

Yes, your answer was very helpful, thank you! I actually have troubles making StructureRepresentation3D change to work correctly.
[Here](https://github.com/hlvlad/onquadro-3d-demo/blob/master/src/MolstarDemoViewer.ts), [demo](https://hlvlad.github.io/onquadro-3d-demo/) I added simple radiobutton to change between three representations. Changing representation in molstar window works normally, but changing it via radiobutton displays only backbone atoms.

**Comment by hlvlad** [comment]
> In your `loadStructureFromData` save the reference to the representation returned by the last commit.
> Then you can do
> 
> ```ts
> pluing.build().to(selector).update(createStructureRepresentationParams(...));
> ```

HIgh @dsehnal, thank you again for detailed answer. I created demo [here](https://hlvlad.github.io/onquadro-3d-demo/), [code](https://github.com/hlvlad/onquadro-3d-demo/blob/master/src/MolstarDemoViewer.ts) with approach you suggested. It generally works, but I am wondering why representation is inconsistent when changed via radio button vs via built in Mol* controls on left panel.

**Comment by arose** [comment]
To get closer to the Mol* Viewer default you should pass the structure object.
```ts
const repr = createStructureRepresentationParams(this.plugin, structure.data, props);
```

For files that contain just a partial dna/rna you might want to show only the Nucleotide Block visual in the cartoon representation. See also `src\mol-repr\structure\representation\cartoon.ts`
```ts
props = {
    type: type,
    typeParams: {visuals: ['nucleotide-block']},
    color: coloring,
    size: 'uniform',
    sizeParams: {value: 2.0}
}
```

**Comment by hlvlad** [comment]
@arose, thanks, it worked for me.
