### ISSUE TITLE
Save session failed based a .molx file.

### ISSUE THREAD

**Issue by QDMarkMan** [molstar/molstar#1350]
Hi, here is my issue description:

## 1. Issue Description

When I saved a Session based on a .molx file, all of my **pdb componets changes** were lost.

## 2. Environment
molstar: [The latest version]

## 3. Demo file
> The file suffix needs to  be changed as .molx

[mol-star_state_2024-11-19-16-42-39.txt](https://github.com/user-attachments/files/17812185/mol-star_state_2024-11-19-16-42-39.txt)

**Comment by QDMarkMan** [comment]
For example, the Opacity of 3D representation and the theme color.
![image](https://github.com/user-attachments/assets/b58cbcef-d12b-486a-8578-1214b55fb993)

**Comment by dsehnal** [comment]
I tried this with .mvsx now and both transparency and color are preserved when re-loading the file.

Maybe the issue is that you were not saving the latest snapshot? You have to overwrite the state snapshot manually if there has already been one previously created:

![image](https://github.com/user-attachments/assets/238639de-77af-42f4-af9a-5013c35744f8)

Basically what's happening is that the first time you click the "save session" button a snapshot of the state is created. If you then make further changes, this snapshot is not automatically overwritten but instead it has to be done manually.

I do agree this is not the ideal UX .. and I though I've improved this by always doing latest snapshot on save if there was only one "active". Should double check this.

**Comment by dsehnal** [comment]
Think I found the issue, fix in https://github.com/molstar/molstar/pull/1359

**Comment by QDMarkMan** [comment]
Thank you for your help! It would be even better if the UX were easier to use.

**Comment by QDMarkMan** [comment]
Glad to hear that! I’ll give it a try.
