### ISSUE TITLE
How to assign data from Pfam annotaition to mouseover labels?

### ISSUE THREAD

**Issue by daenbol** [molstar/molstar#136]
I would like to do something like here. What is the best way to do that?

![image](https://user-images.githubusercontent.com/53538336/110534869-9ef1eb80-8130-11eb-9b13-b40f5575ba7f.png)

**Comment by dsehnal** [comment]
- Add a label provider. [Here's how](https://github.com/molstar/molstar/blob/master/src/extensions/pdbe/structure-quality-report/behavior.ts#L26) it is handled for PDBe Structure Validation report. 
- To be able to reference the data, you might need to add a [custom property that stores the data](https://github.com/molstar/molstar/blob/master/src/extensions/pdbe/structure-quality-report/prop.ts#L29) 
  - If you are displaying just a single structure and don't want to spent too much time on it (since the above point takes take of downloading, parsing and transforming the date), it's probably good enough to use some global state that stores the annotations. Good place where to store it is the [PluginContext.customState](https://github.com/molstar/molstar/blob/master/src/mol-plugin/context.ts#L185) property (e.g. ``this.plugin.customState[key] = <...>``).

Let us know if you have more questions.

**Comment by daenbol** [comment]
Thank you for answering my question! Unfortunately, that's too complicated for me, I'm completely a newcomer in JS, TypeScript and so on. 
There is already an [example](https://www.rcsb.org/3d-view/5NDW) of usage of making these labels from Pfam annotation on the RCSB Molstar plugin, but there is no annotation in [case](https://www.ebi.ac.uk/pdbe/entry/pdb/5ndw) of PDBe. Why don't just copy a piece of code charged of an annotation which was imported on a page of this structure? 
They additionally use `<script src="https://www.rcsb.org/search/search-data?ts=5385464"> </script>` and directly inserted into a page scripts. 
When I tried to copy-paste a page code to understand what's going on every time it threw an error: `loading '5ndw' failed with 'Error: Invalid data cell.', trying next model-loader-provider`. I tried to find out what caused the error, but I didn't succeed((

**Comment by dsehnal** [comment]
However frustrating it might be, "modern" web development is rarely as simple as including a script and writing a few lines of inline JS.

I can see that PDBe does support some form of Pfam annotations (I couldn't find equivalent functionality in RCSB):

![image](https://user-images.githubusercontent.com/21145776/111070047-285a4280-84d0-11eb-9618-e67286711a9e.png)

PDBe's Mol* wrapper is available at https://github.com/PDBeurope/pdbe-molstar. Maybe you can try using that directly?

**Comment by arose** [comment]
@daenbol were you able to solve your issue?

**Comment by daenbol** [comment]
@arose Yes. Thank you!
