### ISSUE TITLE
Change visibility of custom shapes 

### ISSUE THREAD

**Issue by Ginko-X** [molstar/molstar#162]
Hi, I would like to visualize a convex hull for a structure (a set of triangles that can wrap the structure), and so far I've managed to build all the triangle shapes by modifying the code example https://github.com/molstar/molstar/issues/82#issuecomment-687659919  

In my result I found only a part of the triangles are visible, while the others can become visible only if I rotate the view a bit, for example: 
- in the first picture below: I added three triangles in the view, and they can be all visible 
- in the 2nd picture: then I rotated a bit, only one of them is visible

My question is:
I wish to have them all visible simultaneously (so the closest will cover the furthest), how can I do that? Is there any parameter that can configure this?

Thanks in advance!

<img width="725" alt="图片" src="https://user-images.githubusercontent.com/5687628/114705169-bae83e80-9d27-11eb-88f2-e32f5de2bd4f.png">

<img width="685" alt="图片" src="https://user-images.githubusercontent.com/5687628/114705364-f2ef8180-9d27-11eb-8e32-9e19301a3ccf.png">

**Comment by Ginko-X** [comment]
Attached another screenshot where I added all the triangles trying to wrap the structure (no matter how much I rotate, it's impossible to cover the structure entirely )
<img width="681" alt="图片" src="https://user-images.githubusercontent.com/5687628/114709909-6f389380-9d2d-11eb-82ff-f69403f03276.png">

**Comment by dsehnal** [comment]
Hi,

this is related to the vertex ordering of your convex hull. The vertex ordering for each triangle ``(a,b,c)`` needs to be so that the normal computed as ``(b - a) x (c - b)`` (I hope it's this ordering but as long as it's consistent you will get it right) faces away from the center of the object. Swapping any two vertices changes the direction of the normal.

You can also try using double-sided (set ``doubleSided: true``) in the mesh representation params.

**Comment by Ginko-X** [comment]
Thanks for the quick reply. This makes sense :) 

I managed to get it right by checking if the dot product of the normal and the vector from the center of the object to any vertex of the triangle is consistently positive (or negative). 

This `doubleSided` doesn't seem helpful for my case.
