### ISSUE TITLE
How to change "Sequence of" value?

### ISSUE THREAD

**Issue by arontier-egkim** [molstar/molstar#261]
Dear team,

First of all, I'd like to say thank you for your excellent work!

I have a question though. 

I have two PDBs, one for ligand and the other for receptor which are loaded and merged as instructed here https://github.com/molstar/molstar/issues/185 to see the interaction between them.
(https://github.com/molstar/molstar/blob/master/src/apps/docking-viewer/index.ts#L153)
After two PDBs are merged, I have three on the screen:

1. receptor
2. ligand
3. merged

If I move my mouse on to the merged structure in the drawing, it is highlighted red but the protein sequence is not.
I figured I need to select the third one in "Sequence of" selection. 

My questions are these:

A. How to change the value of "Sequence of" selection box programmingly.
B. Can I hide (1. receptor) and (2. ligand)? 
C. What is the purpose of https://github.com/molstar/molstar/blob/master/src/apps/docking-viewer/index.ts#L169?
D. Is there a way to save merged structure in PDB?

Again, thanks for all your kind answers to and efforts for Mol*!

**Comment by dsehnal** [comment]
Hi,

unfortunately, the state of the view is currently local to the component. Would you be interested in making a PR that moves the state to the ``PluginContext`` instead?

**Comment by dsehnal** [comment]
And regarding your other questions:

> B. Can I hide (1. receptor) and (2. ligand)?

Yes, when you are creating the roots/visuals, you can use the ``setSubtreeVisibility`` function to achieve this.

> C. What is the purpose of https://github.com/molstar/molstar/blob/master/src/apps/docking-viewer/index.ts#L169?

This unselects the structure from this menu:

![image](https://user-images.githubusercontent.com/21145776/130828556-77b1af00-c66a-4a04-b1ca-093717cbfd4d.png)

so that other parts of the UI do not affect it.

> D. Is there a way to save merged structure in PDB?

Currently, only single model structures could be exported. For multi-model support, you would need to write the exporter yourself.
