### ISSUE TITLE
Custom preset to have multiple ligands as separate items in the state tree 

### ISSUE THREAD

**Issue by den-medvedev** [molstar/molstar#289]
Hi
At first thanks for your great work on this viewer.

I'm writing to get your consultation on a question below.

My PDB file may contain more then one ligand. Any ligand in that PDB is identified by unique pairs (residue name and its sequence number), e.g. LIG 1, LIG 2, LIG 3... It can be not LIG always, but other 3-letters codes.

I need to display every ligand as a separate item in the state tree to be able to show/hide e.g. LIG 1 only or apply specific color for LIG 2 only etc. To archive this I'm going to create a custom preset to build LIG 1, LIG 2 etc. from selection queries where I'm going to filter sets by residue name and number.

The point is that I don't know how many ligands are in my file and which 3-letters code can be used for them. Maybe I need to populate the list of such unique pairs (name and sequence num) and then iterate over it to create a single ligands one by one.

Is it possible to get such kind of information from e.g. instances of Structure class I have in the preset? Or probably is there better way to archive this.

It would be really useful if you give me advice.
Thanks a lot.

**Comment by dsehnal** [comment]
Hi,

you can iterate over all the residues in the model and get all that are not water/amk/nucleotide. This should be a good approximation to what you are looking for.

The residue names can be found in ``structure.model.atomicHierarchy.resiues`` and you can find the standard names [here](https://github.com/molstar/molstar/blob/master/src/mol-model/structure/model/types.ts#L241). [Here](https://github.com/molstar/molstar/blob/master/src/examples/proteopedia-wrapper/helpers.ts#L55) is an approximation to how it could be implemented. 

Let me know if you need more help.

David

**Comment by den-medvedev** [comment]
Hi @dsehnal 

Thanks a lot for your super quick answer. I think this information is enough for me to dive into it deeper

**Comment by den-medvedev** [comment]
Hi

Just let you know the suggestions above work for me well.

While I was working on it I came to the conclusion I could sort out all residues which entityType is _non-polymer_ or entitySubtype doesn't match _/(oligosaccharide|lipid|ion)/i_. Would it be the same as getting all that are not water/amk/nucleotide? For examples I have it works, but I'm not sure whether it covers all possible cases.

And another question (actually it doesn't relate to this topic) - is there a way to launch app with option to debug the source code e.g. via Chrome dev tools?

Thanks for your help.

**Comment by dsehnal** [comment]
> While I was working on it I came to the conclusion I could sort out all residues which entityType is _non-polymer_ or entitySubtype doesn't match _/(oligosaccharide|lipid|ion)/i_. Would it be the same as getting all that are not water/amk/nucleotide? For examples I have it works, but I'm not sure whether it covers all possible cases.

Maybe another approach would be to use https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/helpers/structure-selection-query.ts#L643. 

This is used to generate this menu:

![image](https://user-images.githubusercontent.com/21145776/143849271-58d3efc2-72c4-4ffc-b891-1d36207e9b3b.png)

I think this might be exactly what you are looking for and sorry for not pointing you to it sooner.

> And another question (actually it doesn't relate to this topic) - is there a way to launch app with option to debug the source code e.g. via Chrome dev tools?

I am sure there is a way to do this. Would have enable source map loading in the webpack config and perhaps include the TypeScript source code in the NPM package (together with making sure the source maps are correctly mapped to that folder) so that it works there as well.

We disabled source maps in webpack a long time ago because it slowed the build a lot. ``console.log`` together with watch builds have been the goto tool for the debugging (and we have ``setDebugMode`` function too).

If you have some time to figure this out (and perhaps make it accessible via an option) and willing to make a PR with it I am sure it would improve the dev process in the future.
