### ISSUE TITLE
Rejects to Load File with Low Precision Assembly Operations

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#303]
Mol* fails to load 7a3o, an entry which will get released tomorrow.

Precision of `pdbx_struct_oper_list` is quite low, causing the `(1 - det) < 0.005` check to fail:
```
1 'identity operation'       ? ? 1    0     0    0    0     1     0    0    0     0     1     0
2 'point symmetry operation' ? ? 0.49 -0.86 0.00 0.00 -0.86 -0.49 0.00 0.00 -0.00 -0.00 -1.00 -80.13
```

Mol* reports: `Error: Symmetry operator (ASM_2) must be a composition of rotation and translation.`

Ignoring the issues with the source file: Is it intended that Mol* stops loading entirely in cases like this?

**Comment by dsehnal** [comment]
- Mol* requires the operators to be uniform for the geometry lookup data structure to work correctly, that's why the check is there.
- Maybe we can relax this in Mol* 3.0 to show a warning instead since it doesn't really impede the visualization.

As far as I know, this is the only PDB entry where this happens. Would it be an option to fix the matrix precision for this entry? And perhaps add a validation to OneDep to enforce this for future entries (seems like a good idea to have this in place)?

**Comment by JonStargaryen** [comment]
> Maybe we can relax this in Mol* 3.0 to show a warning instead since it doesn't really impede the visualization.

Seems like a good idea if the visualization isn't affected.

> As far as I know, this is the only PDB entry where this happens.

This is a first, yeah.

> Would it be an option to fix the matrix precision for this entry?

Yes, people are working on that as well as tracking down how such low precision values made it to the file in the first place. Should get fixed in the near future.

> And perhaps add a validation to OneDep to enforce this for future entries (seems like a good idea to have this in place)?

Agreed, let's see if the corresponding team implements some check after this incident. I'll try to follow up when I know more.

**Comment by arose** [comment]
> Maybe we can relax this in Mol* 3.0 to show a warning instead since it doesn't really impede the visualization.

If need be we can do a patch release for the latest 2.X. Or would this break anything @dsehnal?

**Comment by dsehnal** [comment]
Shouldn't break anything.

**Comment by arose** [comment]
Changed it to warn instead of throw. Looks like 7a3o has been fix as well.
