### ISSUE TITLE
CIF-core of diamond lacks bonds

### ISSUE THREAD

**Issue by bergwerf** [molstar/molstar#32]
https://www.crystallography.net/cod/9008564.html
Right-click for the Jmol popup menu and pick `Symmetry > Reload {1, 1, 1}`

Here is a screenshot from JSmol and Mol* with the assembly to 'symmetry mates' in Mol*.

![image](https://user-images.githubusercontent.com/4458965/79311033-21603400-7efd-11ea-947a-1bd54223187f.png)

![image](https://user-images.githubusercontent.com/4458965/79311119-3dfc6c00-7efd-11ea-83b6-b9da168e41c3.png)

I don't know how to get the single filled in unit-cell in Mol* as in JSmol. I'm also curious if it is possible in Mol* to create a specific number of repeated unit-cells (e.g. 10x10x1).

**Comment by arose** [comment]
> CIF-core of diamond lacks bonds

I will look into that

**Comment by arose** [comment]
> I don't know how to get the single filled in unit-cell in Mol* as in JSmol. I'm also curious if it is possible in Mol* to create a specific number of repeated unit-cells (e.g. 10x10x1).

Yes, the unitcell and supercell are just presets but you can set min/max ijk to any value you like, for 10x10x1 set max ijk to 9 9 0 and min ijk to 0 0 0.

![Annotation 2020-04-15 092127](https://user-images.githubusercontent.com/272250/79362123-0c82a100-7efb-11ea-8548-0117a8792793.png)
![Annotation 2020-04-15 092249](https://user-images.githubusercontent.com/272250/79362127-0e4c6480-7efb-11ea-9c54-0a0692a1af79.png)

**Comment by arose** [comment]
This fixed in master. Thanks @bergwerf for reporting it.

![9008564 (1)](https://user-images.githubusercontent.com/272250/79380361-3648c180-7f15-11ea-9014-7af221329b24.png)
![9008564 (2)](https://user-images.githubusercontent.com/272250/79380371-3a74df00-7f15-11ea-925f-cec35ee34acd.png)
![9008564 (3)](https://user-images.githubusercontent.com/272250/79380376-3ba60c00-7f15-11ea-9481-909ffa764028.png)
![9008564 (4)](https://user-images.githubusercontent.com/272250/79380380-3cd73900-7f15-11ea-9118-3bafabca7df6.png)
