### ISSUE TITLE
Support loading all blocks from a mmcif file

### ISSUE THREAD

**Issue by arose** [molstar/molstar#329]
Support loading all blocks from a mmcif file, i.e., to show all models. Currently only the first block is loaded. Came up in #251.

**Comment by jxmelody** [comment]
Firstly thank you very much for your excellent work! May I kindly know if this enhancement has been done? I have been struggling with this issue for days. I tried to comprehend this project and wish I could contribute to this. Unfortunately, I found the codebase is too complicated and because of the lack of documents, it is really demanding for me to even start.

Regarding this, I have two main concerns:
1, Do you have a plan to add this feature recently?  If not,
2, Is there a more complete document explaining the code base, eg. what 'State, Viewer, Action, behavior...' represent for? So that we can understand this project more thoroughly and thus contribute to it.
Thanks a lot!

**Comment by dsehnal** [comment]
I've done some basic implementation of this in https://github.com/molstar/molstar/pull/581.

Can you have a look and test if this works for you?

**Comment by jxmelody** [comment]
Hi @dsehnal, thank you so much! I have tried your code and got some improvements. see below, all blocks are merged and pushed into one trajectory and I can switch models. 
<img width="400" alt="image" src="https://user-images.githubusercontent.com/16831407/194791369-1d94204b-0c12-499a-b5f8-660d00d13b8e.png"> <img width="400" alt="image" src="https://user-images.githubusercontent.com/16831407/194791351-6d976fb1-62db-4cfa-9b58-8f6e33b07a53.png">
It really helps in some way, but could you please help to make different blocks into separate trajectories? This is exactly what @arose posted in #251, all blocks are parsed and shown in the State Tree at the same time, and the viewer shows all trajectories too. As @arose said, I found I can do it in the UI, but my single file has 10 blocks, which makes this tedious work. I guess I can do a workaround by adding a series of 'Actions'. Not pretty sure how to do this though.
Appreciated it if you could help or give me more hints!
<img width="400" alt="image" src="https://user-images.githubusercontent.com/16831407/194791791-0a1a3fd2-b32e-404a-9a07-4c16adb594f5.png"> <img width="400" alt="image" src="https://user-images.githubusercontent.com/16831407/194793256-52e45b31-d223-4f41-b8bd-3391a04fefd6.png">

**Comment by dsehnal** [comment]
You can show all models in a trajectory from the UI using a "single" click in the top right part of the UI.

**Comment by jxmelody** [comment]
hi @dsehnal,
Wow! Thank you soooo much! It finally works! 
For anyone who is encountering this issue or perhaps has the same needs as mine. Here is my workaround:
1, I load all blocks by default. (Change the definition of  ```TrajectoryFromMmCif ``` in https://github.com/molstar/molstar/blob/8776143ec2289618acc241c55a50f75507c2b56f/src/mol-plugin-state/transforms/model.ts see the implementation in https://github.com/molstar/molstar/pull/581. )
2, I used ```loadAllModelsOrAssemblyFromUrl``` defined in https://github.com/molstar/molstar/blob/c5222e4d1d1d3f614b6d9f0a5e023fe16adcd95e/src/apps/viewer/app.ts to load .cif files

Then, it works like a charm!
<img width="1527" alt="image" src="https://user-images.githubusercontent.com/16831407/194801976-6469372e-e961-4e5c-8ec5-561c575045f2.png">
