### ISSUE TITLE
Error in placing symmetry copies in unit cell

### ISSUE THREAD

**Issue by Henklem** [molstar/molstar#340]
I tried to visualize the PDB structure 6y2k in unit cell assembly and detected an error in the translation of two of the copied complexes. They are visualized in a neighbouring unit cell.

**Comment by dsehnal** [comment]
Thanks, indeed it shows 2 extra copies:

![image](https://user-images.githubusercontent.com/21145776/148961245-6ab9b692-11e8-4f00-858f-7c0f3ea77d17.png)

I wonder if this is because of incorrectly set up info the file or something wrong we do, because other strutures do not exhibit this, error, e.g. 1tqn:

![image](https://user-images.githubusercontent.com/21145776/148961444-b448e532-ca89-4323-adb6-aaa7a3761ec2.png)

**Comment by dsehnal** [comment]
Managed to fix it. Will be up soon. ``toFractional`` operator was being applied twice at one point which resulted in the bad offsets.

![image](https://user-images.githubusercontent.com/21145776/148983321-373dfef2-2550-4a69-9194-6fed3b8171be.png)
