### ISSUE TITLE
Performance Impact of Temporal Multi-Sample

### ISSUE THREAD

**Issue by JonStargaryen** [molstar/molstar#382]
The sequence panel is quite laggy after the default multi-sample mode was changed to temporal. This gets intensified if there are additional subscribers to these events.

https://recordit.co/ZA0LVYkZBc

Is it possible to address this or should one just disable multi-sampling when running into this issue? Thanks!

**Comment by arose** [comment]
The quick solution is to disable either multi-sampling or ambient occlusion, either will speed things up considerably. You can even disable both if need be.

Otherwise there are a few things on my todo list
- only do occlusion once when doing multi-sampling
- do half resolution occlusion

**Comment by JonStargaryen** [comment]
OK, will do that for now :)

**Comment by arose** [comment]
Was looking into it some more and there is another issue apart from slow rendering: We will highlight (and render) hover every 15ms. That is causing the trail that plays catch-up with the cursor. 

The relevant code is in https://github.com/molstar/molstar/blob/2509e91f1ac55331e8aead713f87c21800cec850/src/mol-plugin-ui/sequence/sequence.tsx#L58

Instead of using `debounce Time` we can use `throttleTime` with leading/trailing set to true.

```ts
this.subscribe(throttleTime<{ seqIdx: number, buttons: number, button: number, modifiers: ModifiersKeys }>(60, undefined, { leading: true, trailing: true })(this.highlightQueue), (e) => {
```

This will look choppy instead of laggy - pick your poison. I vote for choppy, and you @dsehnal? If it works for you and you like it, @JonStargaryen, please do a PR.

**Comment by dsehnal** [comment]
I am not sure about the throttle, seems to me that creates the same issue as debounce.

Instead of calling the highlight directly, we can also make a queue with capacity 1 instead (where new highlight requests overwriting the existing ones). 

Might have some time to look at it later today.

---

(And small nitpick about the throttle: if you do `obs.pipe(throttle(...))` you will get the typing automatically)

**Comment by dsehnal** [comment]
I tried both the throttle and batch resolve of marking in #383. Let me know if that helps and feel free to include other tweaks there.

**Comment by arose** [comment]
I found a good way to reuse the occlusion buffer when doing multi-sampling for a 2x rendering speed improvement with no quality loss.
