### ISSUE TITLE
Load files remotely

### ISSUE THREAD

**Issue by caioss** [molstar/molstar#46]
Hi,

First of all, I would like to thank you for making this great software.

Now that we are in pandemic times, I was looking for a solution to visualize protein files that are in a remote machine to which I can connect through ssh. I was able to install Molstar on that machine and open an instance of the visualizer at home using ssh port forwarding. My question is: is there a way to load files present on the remote machine into this home instance?

I was trying something like what was described [here](https://amber-md.github.io/pytraj/latest/tutorials/remote_jupyter_notebook) for Jupyter Notebook/NGLView.

Thanks

**Comment by IvoLeist** [comment]
Hello Caioss,

since in pandemic times speed is everything I felt so free to answer you.
Disclaimer: I am not part of molstar but a user(developer) of web apps using NGL.

If you just need the basic visualization features of NGL maybe my Python [Dash](https://github.com/plotly/dash/) component 
could help you (?). Right now, it is based on [ngl](https://github.com/arose/ngl) and should be part of [dash-bio](https://github.com/plotly/dash-bio) [soonish](https://github.com/plotly/dash-bio/pull/496).

But in the future I might port it to Molstar but before these issues
https://github.com/molstar/molstar/issues/20, https://github.com/molstar/molstar/issues/23 need to be adressed.

Good luck with your research!

Best,
Ivo

**Comment by arose** [comment]
Hi @caioss, if you want to use Jupyter Notebook, you need to stick with NGLView as we don't have a Jupyter Notebook plugin yet. Otherwise, Mol* can open either via the browser open dialog or from http. One option is to use sshfs (https://github.com/libfuse/sshfs) to mount the remote data locally, run a https server locally from which to open the files in Mol*.

**Comment by afa32** [comment]
Hi Alexander
Thank you for this amazing work, I am planning to plug this viewer into my database instead of other viewer currently using, is there any way to load structure to mol* from API i have looked into the file in the server directory but still didnt understand it 

Many thanks,

**Comment by arose** [comment]
@afa32 you can use the pre-built viewer. You can built it yourself or get it, for example, from unpgk (https://www.unpkg.com/browse/molstar/build/viewer/). For the API please look at the methods of the viewer class (https://github.com/molstar/molstar/blob/master/src/apps/viewer/index.ts) and the embedded usage example (https://github.com/molstar/molstar/blob/master/src/apps/viewer/embedded.html),
