### ISSUE TITLE
How to manually handle download error? 

### ISSUE THREAD

**Issue by xuzuodong** [molstar/molstar#506]
Hello,

Generally, When using web request API like [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) or [axios](https://axios-http.com/), we can handle errors caused by network like this: 

``` js
try {
  await fetch('url', { ...configs })
} catch (error) {
  console.log(error)
}
```

If I do similar thing to `plugin.builders.data.download()`, error cannot be caught: 

``` js
try {
  const data = await plugin.builders.data.download({ url: molPath }, { state: { isGhost: true } })
} catch (error) {
  console.log(error) // when network not ok, code here won't be excuted
}
```

Seems that error has been caught internally, so I can't manually handle it when the request fails. Is there any way to do so?

Thanks!

**Comment by dsehnal** [comment]
Hi, 

- you can download the data yourself via fetch or axios and pass it to mol* as .data (or maybe .raw, not sure from the top of my head) instead of .download in the builder class. 
- Another option is to check for the contents of the cell from the download operation. The node will have error status and also contains an error field too. It doesn't throw an error but you can use if condition to check.

**Comment by xuzuodong** [comment]
Thanks for your quick response! I took the first way and it's perfectly done.

**Comment by xuzuodong** [comment]
For those who are facing the same issue, the API is `plugin.builders.data.rawData()` BTW.
