### ISSUE TITLE
Surfaces not showing in Safari

### ISSUE THREAD

**Issue by kjelljorner** [molstar/molstar#523]
This is demo of the alpha orbitals is not showing in Safari Version 15.5 (17613.2.7.1.8).

https://molstar.org/demos/alpha-orbitals/

The data is definitely there as they can be "shown" by turning on the outline

<img width="1219" alt="image" src="https://user-images.githubusercontent.com/36157530/184884941-ff14a66c-3814-4c00-9def-976af3379fb0.png">

I made some experiments with my own example and turning off GPU seems to render the orbitals.

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/36157530/184885342-e79c1d32-ea3d-4222-8966-f82189b4a991.png">

Also using wireframe works

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/36157530/184885520-b9c86fed-b9ec-4f72-b76d-fbd1da54f7f0.png">

**Comment by dsehnal** [comment]
Thanks for the info, seems like they changed something in Safari yet again. I am not sure when I will get to fixing this (or if it fixes itself in a future version).

**Comment by arose** [comment]
There is some issue with Safari >= 15.4 when rendering meshes with data from textures and using WebGL2. The error is a plain "Internal error compiling shader with Metal backend'. Using WebGL1 is still OK (can be forced by using the preferWebgl1 setting).

Maybe I will track down the issue and report it to safari. For the time being I changed it so that webgl1 is prefered for 15.4 and 15.5 as well, see e697624064502860a3c2d01d8e53ce32f74501df.

**Comment by kjelljorner** [comment]
Thanks @arose, it's already working. For the [demo](https://molstar.org/demos/alpha-orbitals/) it's not, but I suspect it's still using the older version.

**Comment by arose** [comment]
fix/workaround in v3.14.0, reported bug in safari https://bugs.webkit.org/show_bug.cgi?id=244152
