### ISSUE TITLE
Working with state - documentation

### ISSUE THREAD

**Issue by tomasz-sodzawiczny** [molstar/molstar#561]
Hi! I just started working with molstar (using it as a lib/plugin in my application), and it's a bit hard to understand how to interact with the state of the viewer. The code is quite nice and readable, but it is complex, so understanding from there is time consuming. I found [docs/state](https://github.com/molstar/molstar/tree/master/docs/state), but it doesn't seem complete.

What would be the best way to learn about it? Are there some good code examples available? I would want to e.g. observe currently selected entities.

I'm happy to contribute to the docs, once I understand the mental model bit more.

This might be relevant for https://github.com/molstar/molstar/issues/559 too.

**Comment by dsehnal** [comment]
Hi Tomasz,

- most of the interactions are available through the behaviors in the `PluginContext`: https://github.com/molstar/molstar/blob/master/src/mol-plugin/context.ts#L83
- different modules of the code then subscribe to these (usually added as behaviors in the `PluginSpec`, for example here https://github.com/molstar/molstar/blob/master/src/mol-plugin/behavior/dynamic/selection/structure-focus-representation.ts#L188
- code in https://github.com/molstar/molstar/tree/master/src/mol-plugin-state/builder contains wrappers that help modify the Mol* state tree

Feel free to ask for more pointers and of course help with documentation would be most welcome.

**Comment by dionjwa** [comment]
Related to this issue: how would I get and set programmatically camera/entity rotation and zoom ?

**Comment by samirelanduk** [comment]
Tomasz's point about understanding the mental model is a crucial one here. I notice a common response to questions about the documentation is 'it would be great if the users could help with the documentation' but that's not really possible because the core concepts of molstar aren't really explained anywhere and it's impossible to really do anything other than what's in the code examples without hours and hours of going through the very complex codebase.

This kind of documentation about core concepts can only be done by the project owners, and without it 99% of the utility of this library is lost. This is one of the most powerful, well-put-together, well written libraries in the biosciences that I've come across, and it's so frustrating that so much of it's potential is not accessible.

**Comment by dhrblav** [comment]
May I again kindly but strongly suggest Mol* project owners to provide an architecture document at a conceptual level, using only few words and pictures in a simple slideshow?
As Sam suggests, once we understand core concepts we, library users, will be happy to contribute more documentation and go into details. As an example I have started drawing some diagrams about  a specific Mol* topic: Interactions data structures. I would be happy to share them, but we first need core concepts to efficiently contribute.

**Comment by cmdcolin** [comment]
code examples like these in the ngl world were/are quite helpful http://nglviewer.org/ngl/gallery/

not sure if similar thing exists for molstar

**Comment by Marwa-Da** [comment]
> May I again kindly but strongly suggest Mol* project owners to provide an architecture document at a conceptual level, using only few words and pictures in a simple slideshow? As Sam suggests, once we understand core concepts we, library users, will be happy to contribute more documentation and go into details. As an example I have started drawing some diagrams about a specific Mol* topic: Interactions data structures. I would be happy to share them, but we first need core concepts to efficiently contribute.

Hi dhrblav, would mind sharing them with me, please?

**Comment by dhrblav** [comment]
Here they are
[MSInteractions.drawio.pdf](https://github.com/molstar/molstar/files/12091724/MSInteractions.drawio.pdf)
