### ISSUE TITLE
Pass a list to custom color theme 

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#599]
I'm trying to make a custom color theme that accepts a list of numbers or objects. I was looking into params-definition to search something suitable for my needs but I am unsure on what to use. Can I pass the list as a reference to the color theme params in any way?

**Comment by arose** [comment]
There is `ParamDefinition.ObjectList` which gives you an UI but you will need to wrap your numbers each in an object.

There is also `ParamDefinition.Value` which works for any value (should be JSON serializable or use a `File`/`Blob` to work with the state management) but does not offer a UI.

Otherwise you can suggest a new `ParamDefinition.NumberList` and a UI for it.

**Comment by giagitom** [comment]
Thanks!
