### ISSUE TITLE
Opaque background blending issue

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#618]
Hi @arose, I spotted an other artifact in a precise configuration (here is the test project [test.molj.txt](https://github.com/molstar/molstar/files/9990550/test.molj.txt))

To reproduce this it's necessary to apply the following configuration:
- enable dpoit
- set dpoit iterations to 1 (this helps to better detect the issue since the first and the last depth layers are peeled. If increased the issue gradually decreases)
- enable fog
- increase fog intensity
- set transparent cartoons 
- enable transparent backfaces on cartoons

Maybe this could be due to a wrong fog blending on backfaces only? I'm not sure the issue has something to do with dpoit.

![image](https://user-images.githubusercontent.com/20627977/201350193-91bc6d80-5f40-4540-9633-903770cd520d.png)

**Comment by arose** [comment]
Some observations. I don't see the issue with wboit or blended. Also with enough layers it seems to go away for dpoit. As far as I can tell the issue exists also with transparent backfaces off or with doublesided off.

I don't have any immediate ideas. Maybe it is a genuine dpoit artifact, because 1) it goes away with enough layers and 2) fog is implement by changing the opacity.

**Comment by giagitom** [comment]
I see, yes this is definitely a dpoit artifact. Maybe is something related to the blending of back and front color buffers?

**Comment by giagitom** [comment]
@arose, After some digging I think this artifacts aren't a bug. It seems to be a normal behavior of Depth peeling. So I would close this issue if you agree.
