### ISSUE TITLE
Difference in ligand interactions between pdb and cif

### ISSUE THREAD

**Issue by jpattle** [molstar/molstar#626]
Hello,

I have observed that there is a difference between the interaction features assigned to atoms in a ligand when loading a pdb verses loading a cif file.

As an example, [1udt](https://www.ebi.ac.uk/pdbe/entry/pdb/1udt) loads differently into Mosltar if you download the '[PDB file](https://www.ebi.ac.uk/pdbe/entry-files/download/pdb1udt.ent)' verses downloading the '[updated mmCIF file](https://www.ebi.ac.uk/pdbe/entry/pdb/1udt#:~:text=Archive%20mmCIF%20file-,Updated%20mmCIF%20file,-PDB%20file%0APDB)' from the ebi site for that structure.

The image below shows the carbonyl oxygen for the pdb file of 1udt as having both the Hydrogen Acceptor and Hydrogen Donor interaction features.

![Screenshot 2022-11-18 at 13 41 28](https://user-images.githubusercontent.com/84507154/202718854-2f32f7c6-1965-4bc8-978e-a0edd626a27d.png)

The image below shows the carbonyl oxygen for the cif file of 1udt as having only the Hydrogen Acceptor interaction feature (which is correct).

![Screenshot 2022-11-18 at 13 42 35](https://user-images.githubusercontent.com/84507154/202719015-32ad2ac5-1ba6-4939-98dc-2a3cc2d179a8.png)

There are also differences for the aromatic nitrogen in the ligand, as the pdb file shows them as having a positive charge, where as the cif does not.

We see similar issues when using proprietary pdb files.

Is this an issue in the parsing of pdb files?

Thanks,

Jason

**Comment by arose** [comment]
I suspect that is due to different bond orders of the marked oxygen-carbon bond. You need to provide bond orders. This can be done in mmcif file using the `_chem_comp_bond` category. There is nothing officially for bond orders in the pdb format. Sometimes a  convention (Interpret CONECT records where the 'to' atom is given multiple times as double/triple bonds, e.g. CONECT 1529 1528 1528 is a double bond.) is used but that is not implemented in molstar, however, a PR to add that would be OK. Finally, you may implement something in molstar to derive bond orders, see #36.

**Comment by arose** [comment]
@jpattle does the above comment explain what you observe?

**Comment by jpattle** [comment]
@arose Yes - sorry for leaving this open ended. We are going to attempt to make use of the mmcif format instead to resolve this issue. If we are unable to and I need to implement CONECT records or bond order derivation I'll get in contact in a separate issue. I'll close this one, thank you for your help.
