### ISSUE TITLE
Loading coordinates frame by frame

### ISSUE THREAD

**Issue by d-beltran** [molstar/molstar#698]
Hi everyone,

I have to load a trajectory in my web server using Molstar. Trajectory data is streamed so I should be able to start loading some frames before the whole trajectory has been downloaded. Is there a canonical way to load extra frames in an already working trajectory? I suppose people from MDsrv are doing something like this?

If not, in NGL we were doing it by writing coordinates directly in the NGL trajectory object. I have been snooping the Molstar plugin and I cannot find where coordinates are stored. Any clue would be very appreciated.

Regards

**Comment by dsehnal** [comment]
This isn't implemented natively yet, but there if the [Trajectory interface](https://github.com/molstar/molstar/blob/master/src/mol-model/structure/trajectory.ts#L20) to help support this functionality.

A possible solution could be to implement a `StreamedTrajectory` which queries and caches your frames dynamically and a corresponding transform that creates the streaming object so that [ModelFromTrajectory](https://github.com/molstar/molstar/blob/master/src/mol-plugin-state/transforms/model.ts#L470) can be used on this. Something like this:

```ts
const Factory = StateTransformer.builderFactory('my-namespace')

const StreamingTrajectory = Factory({
    name: 'streaming-trajectory',
    display: ...,
    from: ...,
    to: SO.Molecule.Trajectory,
    params: {
        url: PD.Url(),
        ...
    }
})({
    ...
})
```
