### ISSUE TITLE
Unexpected hydrogen bond perception

### ISSUE THREAD

**Issue by ljmartin** [molstar/molstar#718]
Hi Molstar, 
I love the implicit hydrogen bond detection used in Molstar. Looking into it I found a hydrogen bond that I think shouldn't be there even with implicit hydrogens and relaxed geometric cutoffs, although I can't figure out why it _is_ being detected. The example I found is in 1X7A: https://www.rcsb.org/3d-view/1X7A?preset=ligandInteraction&label_asym_id=C

The amide nitrogen of the ligand is showing a H-bond to the carbonyl of Gly206, which is pretty much directly behind it. 

Looking through the code, I see that this [nitrogen should be three valent and neutral](https://github.com/molstar/molstar/blob/8c417ef35ce1d6c63712ed5b331423812a1cfc9d/src/mol-model-props/computed/chemistry/valence-model.ts#L92) (i.e. with 1 hydrogen). This hydrogen can be placed explicitly based on the surrounding bonds. If I do this (in another program) the Don-H-Acc angle is ~45 degrees, where 180 degrees would be optimal and 90 degrees would be quite generous. 

Is there any reference or protocol explaining how H-bonds are defined? 
Thanks
Lewis

**Comment by arose** [comment]
I think the issue is that the ligand N in question is not recognized as part of a conjugated group because the neighboring C-O has no double bond whereas it should. Unfortunately the standard pdb archive mmcif files do not contain bond order information (even though they are available in the PDB chemical component dictionary). Mol* has a bond order table for standard amino acids and nucleotides but it is not feasible for ligands. You can get an "updated" mmcif file from PDBe (e.g. https://molstar.org/viewer/?pdb-provider=pdbe vs https://molstar.org/viewer/?pdb-provider=rcsb) which contains the bond orders and it looks good to me.

FYI @JonStargaryen @valasatava

**Comment by ljmartin** [comment]
Thanks @arose - that's a reasonable explanation. For my own purposes, this solves the issue, however I would be interested if you could explain where to find the ligand definition without using the chemical component dictionary. Is there another database of ligands (which would lack the amide bonding in this case) somewhere?

**Comment by arose** [comment]
Not sure I fully understand your question or what you want to achieve. The chemical component dictionary (https://www.wwpdb.org/data/ccd) is something the PDB maintains and is contains proper definitions for any component (amino acid, nucleotide, ligand, ion, ...) used in files within the PDB archive. There are other databases of small molecules, including [pubchem](https://pubchem.ncbi.nlm.nih.gov/) and [drugbank](https://www.drugbank.com/) that provide various chemical definitions.

**Comment by ljmartin** [comment]
Sorry, to be more clear: If the chemical component dictionary has the correct amide bonding (leading to correct hydrogen bond perception, or lack thereof), then what ligand is the RCSB website using? Is it fetching a ligand with incorrect bonding? 

In other words, what is the "standard pdb archive mmcif files" if it isn't the chemical component dictionary?
