### ISSUE TITLE
Residue rainbow coloring pdb format

### ISSUE THREAD

**Issue by bioinsilico** [molstar/molstar#72]
Residue rainbow coloring does not behave as expected when N-terminal residue numbering starts at large indexes in pdb format files. In the attached file the full ribbon is displayed in red

[101M.pdb.zip](https://github.com/molstar/molstar/files/4939310/101M.pdb.zip)

**Comment by arose** [comment]
Yeah, that's because the rainbow color theme uses the sequence-id (also the name of the theme...) defined for polymers but that is not given in pdb format files. For reasons of side effects the pdb format readers just uses the residue number as the sequence id which leads to the problem you are observing.

**Comment by arose** [comment]
added a fix that needs some testing, especially with multi chain .pdb file examples

**Comment by bioinsilico** [comment]
Thank you Alex! I will test that

**Comment by arose** [comment]
Hey @bioinsilico, does this work for you now?

**Comment by bioinsilico** [comment]
@arose Yes, this worked in our tests, thank you!
