### ISSUE TITLE
Way to traverse through slices of a volume

### ISSUE THREAD

**Issue by gfrn** [molstar/molstar#801]
Hello! I need to traverse through 2D slices of a 3D volume representation on a given, set axis (say, f(x,y), axis z), and I've poked around the code to find proper representations and transformers that output the desired view, and the closest I've gotten were `volumeRepresentations` of type `slice`.:

```ts
const repr = molstar
        .build()
        .to(volume)
        .apply(
          StateTransforms.Representation.VolumeRepresentation3D,
          createVolumeRepresentationParams(molstar, volume.data!, {
            type: "slice",
            typeParams: {dimension: ...},
          })
        );
```
That partially works, in the sense that it renders a two dimensional plane onto which the volume is projected, however, it does not seem like the best way. Is there a better to traverse through slices across a volume?

**Comment by dsehnal** [comment]
Do you need to traverse over the data or the visuals? Because these are two different problems.

- For the visuals, your approach is correct to create the initial visualization. For subsequent changing of the slices, you can use something like:

```ts
const repr = ...apply(params).selector; // or await .commit()

// ....

await molstar.build().to(repr).update(newParams).commit();
```

- For data, you can use the properties in `volume`. The `Tensor` namespace is used there to represent the data which always normalizes the axis order to be canonical XYZ.

**Comment by gfrn** [comment]
My apologies for not clarifying, I was indeed thinking of traversing over visuals. Many thanks for confirming!

Is there a way to output these to either a blob or an image directly?

**Comment by dsehnal** [comment]
You can use the screenshot helper on the plug-in context to render to images, yes.

Alternatively, you can check the headless plug-in context and its usage in the examples to run the whole thing using nodejs.
