### ISSUE TITLE
Ligands not displayed by default for pdb entries

### ISSUE THREAD

**Issue by luckyxutao** [molstar/molstar#816]
*  not display ligand water
<img width="1448" alt="image" src="https://github.com/molstar/molstar/assets/1294316/74869a45-f6d2-4a56-a9cd-2e108056c5e5">

* ngl /maestor/molstar(2.0.2) can display
<img width="1107" alt="image" src="https://github.com/molstar/molstar/assets/1294316/daef9ecc-15c8-4574-8fb0-ba75affff4c4">
Can you tell me why molstar(3.32) can not display the ligand water for pdb formart? very thanks~

**Comment by dsehnal** [comment]
This is an unfortunate artifact of our PDB parsing code, which generates new `label_asym_id` for the water and ligand molecules. Combined with the assembly being defined in the archive PDB files, this results in the atoms not displaying. A short-term solution is to:
- use CIF format
- select `Model` type instead of assembly (image below)
- remove the assembly remark from the PDB file

I put up a PR https://github.com/molstar/molstar/pull/817 with fix.

![image](https://github.com/molstar/molstar/assets/21145776/d2fb5108-5ec6-4649-8498-9014941990b8)

**Comment by luckyxutao** [comment]
I see，I am pleased to receive your reply very thanks~
