### ISSUE TITLE
Event for drawing and loading completion

### ISSUE THREAD

**Issue by drizhina** [molstar/molstar#824]
Hi guys. is there an event to track when the files are loaded and drawn to scene?
I want to track down when the structure is loaded and done drawing

**Comment by dsehnal** [comment]
What functionality are you trying achieve?

This might be a little tricky in general since the visual creation happens asynchronously after the state tree has been reconciled. Depending on what you are trying to achieve these things can help you:

- There is a `commited` event in the `canvas3d` object
- You can await the state update for loading the structure
- There might some other options depending on what you are trying to achieve

**Comment by drizhina** [comment]
thanks for the answer. I need an event where everything is done drawing so that screenshot can be saved or the contents of the canvas could be copied to another canvas

**Comment by dsehnal** [comment]
Something like this should work:

```ts
plugin.animationLoop.stop();
const update = plugin.build();
...
await update.commit();
await plugin.animationLoop.tick(0);
plugin.canvas3d!.commit(true);
// save image
plugin.animationLoop.start();
```

You can have a look at the headless renderer too https://github.com/molstar/molstar/blob/master/src/examples/image-renderer/index.ts#L43. You should be able to modify this for in-browser usage.
