### ISSUE TITLE
Improve transparency

### ISSUE THREAD

**Issue by legnes** [molstar/molstar#83]
**Problem**
Transparency at high opacity results in depth artifacts.

<img width="410" alt="Screen Shot 2020-09-08 at 11 45 53 AM" src="https://user-images.githubusercontent.com/1813467/92498642-deaf3900-f1c8-11ea-8e87-750e098f9625.png">

I figured I'd write up some common solutions in case it's helpful to have them all in one place! I kind of think McGuire's weighted OIT is the way to go, but I'd be curious to know what other people think, to hear if I missed any options, etc.!

**Sorting**
One option would be to sort cpu-side.
_Pros:_ Very straightforward shader code-wise. Also, sorting can bring benefits to other parts of the engine, like culling.
_Cons:_ Can be expensive and hard! What if triangles or submeshes intersect/wrap around each other?

**Alternate blend modes**
This would be something like: using a multiply blend mode in combination with rim lighting to simulate tinted volumes.
_Pros:_ Cheap and easy.
_Cons:_ This would be an active decision to adopt a different look for transparency. Good? Bad?

**Depth peeling**
One or two passes per peel, using previous pass's depth buffer as a min/max depth.
_Pros:_ Potentially the most accurate results.
_Cons:_ Can be a lot of passes! Takes a bit of wiring cpu-side (flip-flopping). Might only be viable in webgl2 (multiple render targets)?

**Depth-weighted OIT**
McGuire http://jcgt.org/published/0002/02/09/
_Pros:_ Happy medium of cost/fidelity.
_Cons:_ Would need to build out a section of pipeline specifically for transparency.

**Moment-based OIT**
Münstermann https://cg.ivd.kit.edu/english/mboit.php
_Pros:_ A different, possibly more desirable tradeoff between cost & fidelity than McGuire. Has the possibility to extend to shadows.
_Cons:_ A little more complex than McGuire. Also might require two passes per transparent submesh?

**Comment by dsehnal** [comment]
How about **Depth-weighted OIT** for devices that support multitarget rendering?

**Comment by legnes** [comment]
Hm, why would that need multitarget?

**Comment by dsehnal** [comment]
Seems like I got something mixed up, I should probably go sleep :)

**Comment by legnes** [comment]
Yup, turns out I just didn't read! That said, it looks like they only need five channels, so if we can save one color channel, for example, it could fit in a single target. One way I've seen that done is converting to an optically friendlier color space and checkerboarding. You lose a little bandwidth in the composite step, but possibly worth it to be able to support webgl1?

**Comment by legnes** [comment]
Another nice read https://developer.nvidia.com/content/transparency-or-translucency-rendering

**Comment by arose** [comment]
I vote for **Depth-weighted OIT**.

A couple of years ago I did a prototype in three.js, see https://github.com/mrdoob/three.js/issues/4814 and https://raw.githack.com/arose/three.js/oit/examples/webgl_oit.html.

Cesium is supporting that method as well successfully for while, see https://github.com/CesiumGS/cesium/blob/master/Source/Scene/OIT.js.

- For WebGL2 and WebGL1 with MRT support it is one render pass for the transparent objects; for vanilla WebGL1 we need two render passes. Both need a compositing pass. I am OK with supporting vanilla WebGL1 that way. We do an extra pass to get the depth buffer for vanilla WebGL1 and it works OK.
- Since this involves a compositing step we should add an anti-aliasing post-processing step, e.g. FXAA (added #84).
- It would be nice to write the depth of the transparent objects so it is available for post-processing effects.

**Comment by arose** [comment]
Here is an example of depth-peeling in WebGL https://discourse.threejs.org/t/depth-peel-and-transparency/5365 and demo https://raw.githack.com/pailhead/three.js/depth-peel-example/examples/webgl_materials_depthpeel.html.

The great aspect of depth peeling is that you can limit the layers which can help reduce visual clutter.

**Comment by arose** [comment]
Quick update. Thanks to the great work of @AronKovacs (#98 and #101) the wboit option is available. It is not enabled by default while we evaluate how to best handle anti-aliasing (since hardware MSAA is not readily available with wboit or post-processing effects that write to render-targets).

Surfaces are blended nicely for high opacity values:

![image](https://user-images.githubusercontent.com/272250/101270942-04e66580-3733-11eb-9133-f2415a71ea5b.png) ![image](https://user-images.githubusercontent.com/272250/101270945-0d3ea080-3733-11eb-94c6-e736d4822beb.png)

Self intersection artifacts are gone:

![image](https://user-images.githubusercontent.com/272250/101270994-ae2d5b80-3733-11eb-9e52-57aca8226da3.png) 
![image](https://user-images.githubusercontent.com/272250/101270995-b4233c80-3733-11eb-8d56-bc55844a5b82.png)

The implementation also supports objects that are in part transparent and in part opaque. This comes with a at most 2x performance penalty for that object as it needs to be rendered twice with discards in the fragment shader.

![image](https://user-images.githubusercontent.com/272250/101271284-5512f700-3736-11eb-9912-e727375fe66b.png)

The wboit implementation requires `draw_buffers`, `depth_texture`, `texture_float`, `color_buffer_float` as extensions or built-ins. If not available fully transparent object will be drawn with naive blending as before and partially transparent object will use screendoor transparency as a fallback. The `draw_buffers` and `depth_texture` requirements could be worked around at the expense of additional render passes for transparent objects.

**Comment by arose** [comment]
enabled by default (when supported) since 1.5
