### ISSUE TITLE
Ligands (carbohydrates) not displayed by default for some pdb entries

### ISSUE THREAD

**Issue by bioinsilico** [molstar/molstar#85]
For complex with ligands, the default 3D view by Mol*  shows the ligands as stick model. 
If the ligands are carbohydrates, the default 3D view then show carbohydrate view of such ligands. 

But for entries such as 6WPS/6WPT, the default 3D view does not show either.  There are carbohydrate in these entries, yet the 3D view only show protein. I can select carb and view them in either way, which means the 3D view can function but the default setting may be improper.

**Comment by arose** [comment]
That is due to the preset deciding based on residue count weather to show ligands or not. It is currently stopping to show ligands when there are more than 3000 residue (https://github.com/molstar/molstar/blob/master/src/mol-model/structure/structure/structure.ts#L1108-L1123). I will increase that to 5000. You can also change it in the plugin config (https://github.com/molstar/molstar/blob/master/src/mol-plugin/config.ts#L22-L54) which you can set when create the plugin (config defaults are part of the plugin spec).

**Comment by bioinsilico** [comment]
@arose Thank you for this change en the info

**Comment by arose** [comment]
you're welcome, should be in a release soon
