### ISSUE TITLE
Error when trying to highlight with `plugin.managers.interactivity.lociHighlight.highlightOnly`

### ISSUE THREAD

**Issue by luna215** [molstar/molstar#850]
## Description

Hi, 
I have a custom function that allows me to highlight specific structures I have loaded.

```typescript
async highlightStructure(structureLabel: string) {
    const structure = this.structures[structureLabel];

    if (!structure) {
        console.log(`Could not find structure ${structureLabel}`);
        return;
    }

    const loci = structure.getLoci();
    if (loci) this.plugin.managers.interactivity.lociHighlights.highlightOnly({ loci });
  }
```

And here is the `getLoci()` function:
```typescript
getLoci() {
    const structure_obj = this.plugin.state.data.selectQ((q) => q.byRef(this.ref));

    if (structure_obj) {
        const data = structure_obj[0].obj?.data;
        return Structure.toStructureElementLoci(data);
    }

    console.log('Unable to get loci...');
    return null;
 }
```

This gives me the following error:
<img width="623" alt="Screenshot 2023-07-02 at 11 32 45 AM" src="https://github.com/molstar/molstar/assets/7971405/4e98dacc-faeb-4a42-9711-d6025794f33a">

However, I believe this was working maybe a few release ago.

**Comment by dsehnal** [comment]
That is a weird error indeed. I don't think I can help you here much from just this snippet, since this seems to be an error on [this line](https://github.com/molstar/molstar/blob/61a294c889fee1769beded57f34bb569f545ecdd/src/mol-model-props/common/custom-structure-property.ts#L35) should never happen since the [`currentPropertyData`](https://github.com/molstar/molstar/blob/61a294c889fee1769beded57f34bb569f545ecdd/src/mol-model/structure/structure/structure.ts#L106) always returns an empty object when called. So there is something weird going on.

**Comment by arose** [comment]
@luna215 did you solve this?

**Comment by arose** [comment]
glad this works for you
