### ISSUE TITLE
.h5 trajectories

### ISSUE THREAD

**Issue by pguillem** [molstar/molstar#886]
Hi everyone.

Are there plans to support the HDF5 trajectory file (from [MDTRAJ](https://www.mdtraj.org/1.9.8.dev0/hdf5_format.html)) in Mol*?.

It has a small footprint and offers all benefits of AMBER NetCDF and XTC in a self contained file (contains topology, coordinates, energy, temperature, and many more variables within the same file).

MDCONVERT can parse to/from h5, but it would be super cool to open directly in Mol* without having to inflate into  bigger, denser file(s) at server side.

If i was to write a plugin or extension for Mol* to support it, where in the code is a good place to start?

Best!
Pedro

**Comment by dsehnal** [comment]
Hi Pedro,

I think something like this would be feasible.

- A quick google search found [jsfive](https://github.com/usnistgov/jsfive) for parsing the HDF5 files. Generally, we try to minimize the 3rd party dependencies in Mol*, but the code is public domain, so we can just copy it to the Mol* codebase (which would require a bit of work converting it to .tsx with possibly using `// @ts-nocheck` or `any` types along the way). A good place for this would be adding a new folder to [mol-io/common](https://github.com/molstar/molstar/blob/911433e056a2e8378148c5c3368101eea06311f9/src/mol-io/common) along with the already present msgpack and netcdf parsers. There might be other/better implementations of HDF5 reader available as well though.
- For reading the trajectory itself, add `mdtraj` folder to [mol-io/reader](https://github.com/molstar/molstar/blob/911433e056a2e8378148c5c3368101eea06311f9/src/mol-io/reader). In general, you can reuse the same principles for this as as the [gro parser](https://github.com/molstar/molstar/blob/911433e056a2e8378148c5c3368101eea06311f9/src/mol-io/reader/gro) with the difference that instead of creating the "columns" from the text tokens in the GRO file, you would be able to just wrap/map the raw data from the HDF5.
- The final step would be adding a `TrajectoryFromMdtraj` transform and a provider. This should be a straightforward modification of the code [here](https://github.com/molstar/molstar/blob/911433e056a2e8378148c5c3368101eea06311f9/src/mol-plugin-state/formats/trajectory.ts#L157).

Alternatively, all of this code could live in the `src/extensions` folder. An example of an extension providing a new format support is the [g3d](https://github.com/molstar/molstar/blob/911433e056a2e8378148c5c3368101eea06311f9/src/extensions/g3d) extension.

Let me know if you have more questions.

David

**Comment by pguillem** [comment]
Thank you David for explaining it in such a great detail!
I'll give it a go!

Pedro
