### ISSUE TITLE
Top,  right , bottom controls 'collapsed' option in regionState

### ISSUE THREAD

**Issue by rdirisio** [molstar/molstar#920]
Hello,

I noticed that the left panel in the controls UI is able to be collapsed on initial load of the molstar viewer using `regionState`. One can do something like:
```
    initial: {
      isExpanded: false,
      showControls: true,
      regionState: {top:"full",left:"collapsed",right:"hidden",bottom:"hidden"},
      controlsDisplay: "reactive" as PluginLayoutControlsDisplay,
    },
```
What I would like to do is used collapsed for left, right, and bottom, but it's only implemented for left. Is it possible, to add as a feature, collapsible options for the other panels?

Thanks!

**Comment by dsehnal** [comment]
The `collapsed` state is allowed for the left panel because of how the icons for the tabs there work. The other panels do not offer this functionality. The other layout elements can be toggled `hidden`/`full` in this control from the UI:

![image](https://github.com/molstar/molstar/assets/21145776/40f857f3-b3aa-40c0-a77e-4dc7a85ed54f)

**Comment by rdirisio** [comment]
Thanks for the quick response. I don't see the option to toggle the right panel there. Is that possible?
