### ISSUE TITLE
Failing initializing context on Firefox 119.0  and Ubuntu 20.04

### ISSUE THREAD

**Issue by giagitom** [molstar/molstar#973]
Here is the error trace. I tried disabling webgl2 but the issue remains

![image](https://github.com/molstar/molstar/assets/20627977/6b039502-9844-416c-a711-38cdc304632a)

**Comment by qpxu007** [comment]
I had a similar issue on an ubuntu 22 based system (mint 21.2) containing a nvidia card with firefox or chrome. 

context.js:382 Error: Could not create a WebGL rendering context
    at Object.fromCanvas (canvas3d.js:169:19)
    at PluginContext.initViewer (context.js:347:108)
    at PluginContext.initContainer (context.js:299:19)
    at PluginContext.mount (context.js:313:19)
    at ViewportCanvas.componentDidMount (canvas.js:36:53)
    at commitLayoutEffectOnFiber (react-dom.development.js:23300:30)
    at commitLayoutMountEffects_complete (react-dom.development.js:24683:9)
    at commitLayoutEffects_begin (react-dom.development.js:24669:7)
    at commitLayoutEffects (react-dom.development.js:24607:3)
    at commitRootImpl (react-dom.development.js:26818:5)


As far as I can tell, webgl worked fine in other testing codes.


The context can be created fine if I created the context without any attributes.
i.e. 

return canvas.getContext('webgl2') as GLRenderingContext | null;

instead of 

return canvas.getContext(id, attribs) as GLRenderingContext | null;

Also it can be created if I set 

plugin-config.allow-major-performance-caveat to true. 

I assume this is software-based rendering and not desirable?

**Comment by giagitom** [comment]
Hmm.. it seems that simply rebooting the system worked for me and solved the problem

**Comment by arose** [comment]
> Hmm.. it seems that simply rebooting the system worked for me and solved the problem

your screenshot says "FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS", I would expect this to be a driver or system state issue

**Comment by arose** [comment]
> I assume this is software-based rendering and not desirable?

yes, that is the default, if your are only working with smaller systems and smaller canvas sizes it can be OK to allow software rendering

**Comment by qpxu007** [comment]
I also noticed a nvidia driver update, so rebooted the machine as well, which didn't help.

The weird thing is that google-chrome worked for one user, but not firefox. For the other users, both not working, even after copied the environments of the that user.
